apiVersion: core.oam.dev/v1beta1
kind: Application 
metadata:
  name: deno-app
spec:
  components:
    - name: deno-runner
      type: deno-runner
      properties:
        repoUrl: https://github.com/bhavyastar/deno-napptive-demo
        entryPoint: main.ts
        ports: 
          - port: 8080
        ingresses:  
          - targetPort: 8080
        allowNet: "true"