apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  annotations:
    version: "v0.0.1"
    description: "Random Quote Generator"
spec:
  components:
    - name: random-quote-generator
      type: webservice
      properties:
        image: bhavyasachdeva/random-quote-generator
        ports:
        - port: 8080
          expose: true
      traits:
      - type: napptive-ingress #Set to napptive-ingress      
        properties:
          name: random-quote  
          port: 8080
          path: /  #(Required) path to be exposed

