apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: Random Quote Generator
  annotations:
    description: "Random Quote Generator"
spec:
  components:
    - name: 
      type: webservice
      properties:
        image: bhavyasachdeva/random-quote-generator
        ports:
        - port: 8080
          expose: true
      traits:
      - type: napptive-ingress # Set to napptive-ingress      
        properties:
          name: random-quote-generator # (Optional) endpoint name 
          port: 8080 # (Required) port  where the service is listening for incoming connections.
          path: / # (Required) path to be exposed
